version: "3.9"
services:
  backend:
    container_name: ApiWPPconnect
    hostname: ApiWPPconnect
    network_mode: bridge
    image: alanmartines/mywhatsapp-api-node-wppconnect:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 9001
      VIEW_QRCODE_TERMINAL: ${VIEW_QRCODE_TERMINAL}
      WHATSAPPVERSION: ${WHATSAPPVERSION}
      DEVICE_NAME: ${DEVICE_NAME}
      AUTO_CLOSE: ${AUTO_CLOSE}
      JWT_SECRET: ${JWT_SECRET}
      VALIDATE_MYSQL: ${VALIDATE_MYSQL}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_DIALECT: ${MYSQL_DIALECT}
      MYSQL_TIMEZONE: ${MYSQL_TIMEZONE}
      BROWSER_WSENDPOINT: ${BROWSER_WSENDPOINT}
    ports:
      - "${PORT}:9001"
