version: '3'

networks:
  mywhatsapp-api:

services:

  backend:
    environment:
      - CHROME_WS=ws://chrome:3000

  chrome:
    image: browserless/chrome:latest
    environment:
      - MAX_CONCURRENT_SESSIONS=${MAX_CONCURRENT_SESSIONS:-1}
    networks:
      - mywhatsapp-api